name: mkdocs-test
on:
  push:
    branches: main

jobs:
  build:
    name: deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v2.3.4
      - name: deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
